---
- block:

  - name: Retrieve Login Credentials
    include_vars: /home/temi/EVE/VXLAN/ansible-code/secret.yaml


  - name: Define Providers
    set_fact:
    provider:
    host: "{{ ansible_host }}"
    username: "{{ creds['username'] }}"
    password: "{{ creds['password'] }}"



  - name: Create the tenant VRF
    with_items: "{{ tenants }}"
    nxos_vrf:
     #provider: "{{ provider }}"
     host: "{{ ansible_host }}"
     username: "{{ creds['username'] }}"
     password: "{{ creds['password'] }}"
     vrf: "{{ item.tenant_name }}"
     vni: "{{ item.tenant_layer3_vni}}"
     rd: auto
     state: present
    when: role == "leaf"

  - name: Enable EVPN address Famly for the tenant
    with_items: "{{ tenants }}"
    nxos_vrf_af:
     #provider: "{{ provider }}"
     host: "{{ ansible_host }}"
     username: "{{ creds['username'] }}"
     password: "{{ creds['password'] }}"
     vrf: "{{ item.tenant_name }}"
     afi: ipv4
     route_target_both_auto_evpn: True
     state: present
    when: role  == "leaf"

  - name: Create internal control VLAN/SVI for the VRF
    with_items: "{{ tenants }}"
    nxos_interface:
     host: "{{ ansible_host }}"
     username: "{{ creds['username'] }}"
     password: "{{ creds['password'] }}"
     interface: "{{ item.tenant_vlan_id }}"
     mode: layer3
     state: present
    when: role == "leaf"


  - name: Configure VRF on SVI Interfaces
    with_items: "{{ tenants }}"
    nxos_vrf_interface:
     host: "{{ ansible_host }}"
     username: "{{ creds['username'] }}"
     password: "{{ creds['password'] }}"
     interface: "{{ item.tenant_vlan_id }}"
     vrf: "{{ item.tenant_name }}"
     state: present
    when: role == "leaf"


  - name: Configure VTEP Interfaces
    with_items: "{{ tenants }}"
    nxos_vxlan_vtep:
     host: "{{ ansible_host }}"
     username: "{{ creds['username'] }}"
     password: "{{ creds['password'] }}"
     interface: "{{ item.nve_id }}"
     host_reachability: default
     source_interface: Loopback0
     source_interface_hold_down_time: 30
     rd: auto
     shutdown: false
    when: role == "leaf"