---
creds:
  username: admin
  password: admin

tenants:
 - tenant_name: vxlan-700001
   tenant_layer3_vni: 700001
   tenant_mcast_group: 225.7.0.1
   tenant_vlan_id: 101
   domain: domain_1
   nve_id: 1

 - tenant_name: vxlan-700002
   tenant_layer3_vni: 700002
   tenant_mcast_group: 225.7.0.2
   tenant_vlan_id: 101
   doamin: domain_2
   nve_id: 2

network_subnets:
  - name:
    network:
    subnet:
    vlan_id:
    layer2_vni:


endpoint_details:
  - attached_host:
    attached_switch:
    switch_interface:
    mode:
    allocated_vlan:

